-- Create database if not exists
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SmartMob')
BEGIN
    CREATE DATABASE SmartMob;
END
GO

USE SmartMob;
GO

-- Create TCFG_PARAMETRI_GENERALI table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TCFG_PARAMETRI_GENERALI' AND xtype='U')
BEGIN
    CREATE TABLE TCFG_PARAMETRI_GENERALI (
        NOME_PARAMETRO NVARCHAR(255) NOT NULL PRIMARY KEY,
        VALORE_PARAMETRO NVARCHAR(MAX) NULL,
        TIPO_PARAMETRO NVARCHAR(50) NULL,
        TIPOLOGIA NVARCHAR(100) NULL,
        COD_LINEA_PROD NVARCHAR(50) NULL,
        DT_INS DATETIME2 NOT NULL DEFAULT GETDATE(),
        DT_AGG DATETIME2 NOT NULL DEFAULT GETDATE()
    );
END
GO

-- Create TCFG_SIGNIFICATI_TIPOLOGIE_PARAMETRI table
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TCFG_SIGNIFICATI_TIPOLOGIE_PARAMETRI' AND xtype='U')
BEGIN
    CREATE TABLE TCFG_SIGNIFICATI_TIPOLOGIE_PARAMETRI (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        TIPOLOGIA NVARCHAR(100) NOT NULL,
        SIGNIFICATO NVARCHAR(500) NULL,
        DT_INS DATETIME2 NOT NULL DEFAULT GETDATE(),
        DT_AGG DATETIME2 NOT NULL DEFAULT GETDATE()
    );
END
GO

-- Create ARTICOLI_CONTROLLO_QUALITA table with ID column
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ARTICOLI_CONTROLLO_QUALITA' AND xtype='U')
BEGIN
    CREATE TABLE ARTICOLI_CONTROLLO_QUALITA (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        COD_ARTICOLO NVARCHAR(100) NOT NULL UNIQUE,
        DT_INS DATETIME2 NOT NULL DEFAULT GETDATE(),
        DT_AGG DATETIME2 NOT NULL DEFAULT GETDATE(),
        COD_LINEA_PROD NVARCHAR(50) NULL
    );
END
GO

-- Insert sample data for TCFG_SIGNIFICATI_TIPOLOGIE_PARAMETRI
IF NOT EXISTS (SELECT * FROM TCFG_SIGNIFICATI_TIPOLOGIE_PARAMETRI)
BEGIN
    INSERT INTO TCFG_SIGNIFICATI_TIPOLOGIE_PARAMETRI (TIPOLOGIA, SIGNIFICATO)
    VALUES 
        ('QUALITY', 'Quality control parameters'),
        ('PRODUCTION', 'Production line parameters'),
        ('MAINTENANCE', 'Maintenance scheduling parameters'),
        ('SAFETY', 'Safety and compliance parameters');
END
GO

-- Insert sample data for TCFG_PARAMETRI_GENERALI
IF NOT EXISTS (SELECT * FROM TCFG_PARAMETRI_GENERALI)
BEGIN
    INSERT INTO TCFG_PARAMETRI_GENERALI (NOME_PARAMETRO, VALORE_PARAMETRO, TIPO_PARAMETRO, TIPOLOGIA, COD_LINEA_PROD)
    VALUES 
        ('MAX_TEMP', '85', 'NUMERIC', 'QUALITY', 'LINE_001'),
        ('MIN_PRESSURE', '2.5', 'NUMERIC', 'PRODUCTION', 'LINE_001'),
        ('INSPECTION_INTERVAL', '24', 'NUMERIC', 'MAINTENANCE', 'LINE_002'),
        ('SAFETY_CHECK_FREQ', '12', 'NUMERIC', 'SAFETY', 'LINE_001');
END
GO

-- Insert sample data for ARTICOLI_CONTROLLO_QUALITA
IF NOT EXISTS (SELECT * FROM ARTICOLI_CONTROLLO_QUALITA)
BEGIN
    INSERT INTO ARTICOLI_CONTROLLO_QUALITA (COD_ARTICOLO, COD_LINEA_PROD)
    VALUES 
        ('ART001', 'LINE_001'),
        ('ART002', 'LINE_001'),
        ('ART003', 'LINE_002'),
        ('ART004', 'LINE_002');
END
GO

PRINT 'Database initialization completed successfully!';
